proxy:
  restart: always
  image: containersol/docker-registry-proxy
  ports:
    - 5000:443
  links:
    - registry:docker-registry
  environment:
    REGISTRY_HOST: docker-registry
    REGISTRY_PORT: '5000'
    SERVER_NAME: localhost
  volumes:
    - certs:/etc/nginx/ssl:ro # expects docker-registry.crt and docker-registry.key
    - .htpasswd:/etc/nginx/.htpasswd:ro
registry:
  restart: always
  image: registry:2
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
    - registry-data:/var/lib/registry
